Added flush to cat_helper.py
GoogleCloudPlatform/gsutil pull request #1528
Opened 2022-06-21 13:53 UTC by ejeselsohn

The gsutil cat -h flag when used on multiple objects which are small, first prints the headers of all the objects the user entered and then prints the contents of all the objects the user entered.
The reason the gsutil cat -h command with multiple small files does not work properly is because the headers are written to stderr whereas the object contents are written to stdout. Since stderr does not have a buffer and stdout does, with small files, the buffer is not cleared fast enough and both headers are printed before the first content is printed. By flushing the buffer immediately, the header of the first object is printed followed by the content, header of the second object followed by the content, etc..

2022-06-21 14:00 UTC, rrauber requested changes
Could you add a test that covers the `flush` call? I think a unit test kind of like [this one](https://github.com/GoogleCloudPlatform/gsutil/blob/master/gslib/tests/test_cp.py#L4902), which mocks out cat_out_fd and ensures `flush` is called after data is written would be a good fit!

Also, could you add a bit more information about the issue you're trying to solve to the title/description? It's helpful when looking through the history.

2022-06-22 18:48 UTC, rrauber approved these changes

2022-06-22 18:49 UTC, merged

2022-06-23 16:38 UTC, NickGoog commented on gslib/tests/test_cat.py
> +    # between Windows OS and Python Version 3.5.
It doesn't really make sense to compare an OS to a Python version. This should be something like `Windows OS Python Version X` to `Other OS's Python Version Y` or `Windows OS Python 3.5 to later Python versions on Windows`

2022-06-23 16:45 UTC, NickGoog commented on gslib/tests/test_cat.py
> +                            object_name='foo',
`foo` and `foo1` isn't as descriptive as something like `foo1` and `foo2`. If you have `foo` without a number, people may assume there's just one of them.

2022-06-23 16:45 UTC, NickGoog commented on gslib/tests/test_cat.py
> +    command_mock = mock.Mock()
Might be more clear to call this `cat_command_mock`