rpo shim support and test parity
GoogleCloudPlatform/gsutil pull request #1616
Opened 2022-11-01 19:16 UTC by pradipm90

rpo shim support and test parity

2022-11-04 14:39 UTC, NickGoog commented
LGTM, will wait for Dilip b/c he has more familiarity with the feature

2022-11-04 15:04 UTC, dilipped requested changes
I think the implementation is incorrect. Feel free to reach out if you have any questions.

2022-11-04 15:04 UTC, dilipped commented on gslib/commands/rpo.py
> +                                  '--rpo',
I will have to take a look at the gcloud CL for rpo. I don't think we should have boolean flags for rpo as the set command accepts strings like ASYNC_TURBO and DEFAULT. Please ping me offline the CL for rpo.

2022-11-04 15:04 UTC, dilipped commented on gslib/commands/rpo.py
> +                      'enforced':
Did you try running the command with use_gcloud_storage=True in boto config? I think it should error out.

2022-11-04 15:04 UTC, dilipped commented on gslib/commands/rpo.py
> +                      'enforced':
Things like these would also be caught by adding a shim translation test like this: https://github.com/GoogleCloudPlatform/gsutil/blob/8cbf3362f34becf358f2fcd60dc3f20bf08a9a17/gslib/tests/test_ls.py#L194

2023-01-05 00:46 UTC, dilipped commented
This is being implemented in a separate PR. Closing this one.

2023-01-05 00:46 UTC, closed without merging